# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# This is the build name, which shows in Azure DevOps and is stamped into the built assemblies
name: '$(versionBase).$(buildNumber)'

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: $[counter('buildNumberCounter', 1)]
  versionBase: '0.2.0'
  releaseVersion: $(versionBase)
  prereleaseVersion: $(versionBase)-alpha.$(buildNumber)
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:

# Use NuGet version >= 4.9.1 so that the nuget pack command works properly
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet v4.9.4'
  inputs:
    versionSpec: '4.9.4'

# Use .NET Core 2.2.203 to get C# 8 support
- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core 2.2.203'
  inputs:
    version: '2.2.203'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Build two NuGet packages, the first with a prerelease version number suffix, always published to the CI feed and
# optionally published to nuget.org for public beta releases
- task: DotNetCoreCLI@2
  displayName: 'Create prerelease NuGet package'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: 'PACK_VERSION'
    packDirectory: '$(Build.ArtifactStagingDirectory)/prerelease'
    verbosityPack: normal
    nobuild: true
  env:
    PACK_VERSION: '$(prereleaseVersion)'

# Build two NuGet packages, the second with a production version number, published to nuget.org when releasing
# (this task is disabled for now, until we actually need it)
- task: DotNetCoreCLI@2
  enabled: false
  displayName: 'Create release NuGet package'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: 'PACK_VERSION'
    packDirectory: '$(Build.ArtifactStagingDirectory)/prerelease'
    verbosityPack: normal
    nobuild: true
  env:
    PACK_VERSION: '$(releaseVersion)'

# Publish to our CI NuGet feed (Azure Artifacts)
- task: DotNetCoreCLI@2
  displayName: 'Publish prerelease NuGet to CI feed'
  inputs:
    command: push
    publishVstsFeed: 'ci-feed'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/prerelease/*.nupkg'
    allowPackageConflicts: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
