title: Fluxx
description: Fluxx functional markup language
theme: just-the-docs

url: https://bretjohnson.github.io/fluxx/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
